const monthName = document.getElementById("month-name")
const dayName = document.getElementById("day-name")
const dayNum = document.getElementById("day-number")
const Year = document.getElementById("year")
const date = new Date()
console.log(date)
const month =  date.getMonth()
monthName.innerText = date.toLocaleString("en",{month:"long"})
dayName.innerText =date.toLocaleString("en", {weekday:"long"})
dayNum.innerText = date.getDate()
Year.innerText = date.getFullYear()
